version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12896
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql://admin:12896@db:5432/resume_db
      SECRET_KEY: WNFKahjBRbxV4qMvZSkIckJKg5fkGrxx-9irGS149K0
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend


volumes:
  postgres_data: